{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Downloader Log Analysis\n",
    "\n",
    "In this notebook we are going to analyze the downloader errors reported in its log file."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## HTTP Error codes\n",
    "\n",
    "We want to retrieve all the possible error codes that are returned by the downloader. "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os   "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [],
   "source": [
    "#open the log file\n",
    "\n",
    "dirname = os.path.dirname(__name__)\n",
    "logs_path = os.path.join(dirname, '../download/logs/downloader_errors.log')\n",
    "\n",
    "log_file = open(logs_path, \"r\", encoding=\"utf-8\")\n",
    "\n",
    "errors_codes = set()\n",
    "\n",
    "while True:\n",
    "    line1 = log_file.readline()\n",
    "\n",
    "    if not line1:\n",
    "        break\n",
    "\n",
    "    line2 = log_file.readline()\n",
    "    line3 = log_file.readline()\n",
    "    line4 = log_file.readline()\n",
    "\n",
    "    split = line3.split(\"Error: \")\n",
    "\n",
    "    errors_codes.add(split[1].strip())\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "No host specified.\n",
      "404 Client\n",
      "406 Client\n",
      "504 Server\n",
      "410 Client\n",
      "502 Server\n",
      "403 Client\n",
      "400 Client\n",
      "503 Server\n",
      "500 Server\n"
     ]
    }
   ],
   "source": [
    "for code in errors_codes:\n",
    "    if len(code) < 20:\n",
    "        print(code)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## HTTP Error Messages\n",
    "\n",
    "We want to retrieve all the possible error messages that are returned by the downloader. "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "HTTPConnectionPool(host='data.colinda.org', port=80): Max retries exceeded with url: /rdf-dump/COLINDA.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcc3dc2fdd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='data.opendataportal.at', port=80): Max retries exceeded with url: /dataset/8fbd4757-68a7-4d2c-bff7-cadf6639b934/resource/175d1d36-02eb-468d-9c13-56dd07506f48/download/registercoreconformanceclasslisalandcoverat.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcc3dc15b90>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPSConnectionPool(host='performance.cityofdavenportiowa.com', port=443): Max retries exceeded with url: /resource/dpxt-b8m4.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fca9edffdd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='data.opendataportal.at', port=80): Max retries exceeded with url: /dataset/8fbd4757-68a7-4d2c-bff7-cadf6639b934/resource/e5393dfc-1d2c-4f21-bbd0-bb9cae7f6049/download/registrymandatoryconformanceclassgbatestat2.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcc3dc173d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='provenanceweb.org', port=80): Max retries exceeded with url: /ns/pml (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca9ee120d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='imash.leeds.ac.uk', port=80): Max retries exceeded with url: /ontologies/amon/CulturalAspects.owl (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca9ee59d10>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='futurewavehosting.com', port=3030): Max retries exceeded with url: /my-family-lineage/query (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca9ee10450>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPSConnectionPool(host='performance.cityofdavenportiowa.com', port=443): Max retries exceeded with url: /resource/n94b-g2ap.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fca9ee5fd90>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='lodcloud.tw.rpi.edu', port=80): Max retries exceeded with url: /purl.org/between-the-edges/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fcc3dc52990>, 'Connection to lodcloud.tw.rpi.edu timed out. (connect timeout=None)'))\n",
      "HTTPSConnectionPool(host='performance.cityofdavenportiowa.com', port=443): Max retries exceeded with url: /resource/aq9a-y9yx.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fca9edd6890>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPSConnectionPool(host='performance.cityofdavenportiowa.com', port=443): Max retries exceeded with url: /resource/v6kp-h5kp.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fca9edff8d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPSConnectionPool(host='performance.cityofdavenportiowa.com', port=443): Max retries exceeded with url: /resource/jfc3-wk6f.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fca9ee5fb90>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPSConnectionPool(host='performance.cityofdavenportiowa.com', port=443): Max retries exceeded with url: /resource/enha-qswz.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fca9ee5dc90>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='sparql.tw.rpi.edu', port=80): Max retries exceeded with url: /vocab/datafaqs (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca9ee44150>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='prtr.ec.europa.eu', port=80): Max retries exceeded with url: /rdf/FacilityID_Changes.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca9ee16a90>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='prtr.ec.europa.eu', port=80): Max retries exceeded with url: /rdf/PollutantTransfer.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca9ee14790>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPSConnectionPool(host='opendata.oorlogsbronnen.nl', port=443): Max retries exceeded with url: /dataset/2b3f0e25-1c64-4f52-a8b0-862816351c0b/resource/90db9718-92da-45c1-bcc0-239c112448d5/download/gvn_niod01.nt (Caused by SSLError(CertificateError(\"hostname 'opendata.oorlogsbronnen.nl' doesn't match 'documentwijzer.raadvanalmere.nl'\")))\n",
      "HTTPSConnectionPool(host='performance.cityofdavenportiowa.com', port=443): Max retries exceeded with url: /resource/bv66-jdqj.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fca9edd7290>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='ckan.net', port=80): Max retries exceeded with url: /storage/f/file/7385068f-e6ca-4400-a61c-d910cf188f0f (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca9ee16350>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='provenanceweb.org', port=80): Max retries exceeded with url: /ns/pml (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca9ee67710>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPSConnectionPool(host='performance.cityofdavenportiowa.com', port=443): Max retries exceeded with url: /resource/y2xh-npbe.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fca9ee5f150>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='sparql.tw.rpi.edu', port=80): Max retries exceeded with url: /vocab/datafaqs (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca9ee6a610>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPSConnectionPool(host='performance.cityofdavenportiowa.com', port=443): Max retries exceeded with url: /resource/hdnn-fgbn.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fca9edfe750>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "[Errno 21] Is a directory: 'datasets/15082/'\n",
      "HTTPSConnectionPool(host='performance.cityofdavenportiowa.com', port=443): Max retries exceeded with url: /resource/de42-rudk.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fca9edfcb50>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "[Errno 21] Is a directory: 'datasets/13357/'\n",
      "HTTPConnectionPool(host='prtr.ec.europa.eu', port=80): Max retries exceeded with url: /rdf/PollutantRelease.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca9ee15350>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPSConnectionPool(host='performance.cityofdavenportiowa.com', port=443): Max retries exceeded with url: /resource/sbvt-8yma.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fca9edefe90>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='ckan.net', port=80): Max retries exceeded with url: /storage/f/file/ac235324-8c78-4cbe-b1e5-a91574f7c570 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca9ee16110>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='provenanceweb.org', port=80): Max retries exceeded with url: /ns/pml (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcc3dc53d50>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPSConnectionPool(host='performance.cityofdavenportiowa.com', port=443): Max retries exceeded with url: /resource/p6bj-nanv.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fca9edd6c50>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPSConnectionPool(host='data.alaska.gov', port=443): Max retries exceeded with url: /resource/fujn-cygq.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fca9edfc290>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='sparql.tw.rpi.edu', port=80): Max retries exceeded with url: /vocab/datafaqs (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcc3dc2d2d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='reference.data.gov.uk', port=80): Max retries exceeded with url: /technical-registry/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca9ee5b210>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPSConnectionPool(host='upgrade-odn.regione.umbria.it', port=443): Max retries exceeded with url: /sparql?default-graph-uri=http://dati.umbria.it/graph/cultura/descrizioni&qtxt=select%20*%20where%20%7B?s%20?p%20?o%7D%20limit%201000 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fca9ee037d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='my-family-lineage.com', port=80): Max retries exceeded with url: /w/images/a/af/BruceWhealtonJr.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca9ee1d990>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "[Errno 21] Is a directory: 'datasets/15786/'\n",
      "HTTPConnectionPool(host='dati.umbria.it', port=80): Max retries exceeded with url: /dataset/826515b8-a19d-4496-99af-e3b9967db130/resource/9ba67744-e844-4ea4-896d-9990ed751982/download/consorzi.rdf (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fca9ee1dc50>, 'Connection to dati.umbria.it timed out. (connect timeout=None)'))\n",
      "[Errno 21] Is a directory: 'datasets/14583/'\n",
      "HTTPSConnectionPool(host='performance.cityofdavenportiowa.com', port=443): Max retries exceeded with url: /resource/rjpy-zs2h.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fca9edd6790>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='prtr.ec.europa.eu', port=80): Max retries exceeded with url: /rdf/facility/11338 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca9ee15990>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='data.colinda.org', port=80): Max retries exceeded with url: /rdf-dump/COLINDA.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca9ee10e90>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "[Errno 21] Is a directory: 'datasets/14603/'\n",
      "HTTPConnectionPool(host='prtr.ec.europa.eu', port=80): Max retries exceeded with url: /rdf/PollutantReleaseMethodUsed.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca9ee45c10>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='wiki.prov.vic.gov.au', port=80): Max retries exceeded with url: /rdf/Public_Record_Office_Victoria_Semantic_Wiki.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca9ee0aa90>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPSConnectionPool(host='data.alaska.gov', port=443): Max retries exceeded with url: /resource/xa3v-4apb.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fca9edfee50>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='my-family-lineage.com', port=80): Max retries exceeded with url: /w/images/6/6c/Sangster_family_tree_2012-06-30.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca9ee136d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='data.opendataportal.at', port=80): Max retries exceeded with url: /dataset/8fbd4757-68a7-4d2c-bff7-cadf6639b934/resource/c1329e61-5564-454a-a93d-d1fc2b8f4590/download/registerautomaticharvestingconformanceclasslisalandcoverclass.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcc3dc14550>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='opendap.tw.rpi.edu', port=80): Max retries exceeded with url: /source/us/file/cr-full-dump/version/latest/conversion/opendap-tw-rpi-edu.nt.gz (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcc3dc15a10>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='provenanceweb.org', port=80): Max retries exceeded with url: /ns/pml (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcc3dc1db90>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='provenanceweb.org', port=80): Max retries exceeded with url: /ns/pml (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca9ee159d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPSConnectionPool(host='performance.cityofdavenportiowa.com', port=443): Max retries exceeded with url: /resource/vqpu-fd7s.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fca9edfea90>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPSConnectionPool(host='performance.cityofdavenportiowa.com', port=443): Max retries exceeded with url: /resource/9cns-rzvq.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fca9edffa50>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "[Errno 21] Is a directory: 'datasets/14344/'\n",
      "HTTPConnectionPool(host='mlode.nlp2rdf.org', port=80): Max retries exceeded with url: /datasets/wals.nt.gz (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcc3dc2e910>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='eol.taxonconcept.org', port=80): Max retries exceeded with url: /data/eol/eol_000001.ttl (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca9ee16190>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='ckan.net', port=80): Max retries exceeded with url: /storage/f/file/e25b0ab3-04cf-442e-abaf-910321e9058f (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca9eded210>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='provenanceweb.org', port=80): Max retries exceeded with url: /ns/pml (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca9edefd50>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='linkedopendata.tw', port=80): Max retries exceeded with url: /geonames/tw-geo-names.nt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca9ee25290>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='sparql.tw.rpi.edu', port=80): Max retries exceeded with url: /vocab/datafaqs (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca9ee5fa90>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPSConnectionPool(host='performance.cityofdavenportiowa.com', port=443): Max retries exceeded with url: /resource/3dxs-628i.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fca9ef95e50>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPSConnectionPool(host='performance.cityofdavenportiowa.com', port=443): Max retries exceeded with url: /resource/4wty-fh8m.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fca9edd5fd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "[Errno 21] Is a directory: 'datasets/13412/'\n",
      "HTTPConnectionPool(host='opendap.tw.rpi.edu', port=80): Max retries exceeded with url: /source/us/file/cr-full-dump/version/latest/conversion/opendap-tw-rpi-edu.nt.gz (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca9ee08b10>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='opendap.tw.rpi.edu', port=80): Max retries exceeded with url: /id/component/olfs (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcc3dc34b90>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='eol.taxonconcept.org', port=80): Max retries exceeded with url: /data/anno/anno_000001.ttl (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcc3dc2f790>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='ckan.net', port=80): Max retries exceeded with url: /storage/f/file/fe3073f5-9533-4f8c-90f3-2c6bc2fc6ece (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca9ee1e890>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='my-family-lineage.com', port=80): Max retries exceeded with url: /w/images/d/d0/Adams.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca9ee1ca50>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPSConnectionPool(host='performance.cityofdavenportiowa.com', port=443): Max retries exceeded with url: /resource/jjwq-t5iu.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fca9edffa50>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPSConnectionPool(host='performance.cityofdavenportiowa.com', port=443): Max retries exceeded with url: /resource/69mt-euys.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fca9edfe2d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='data.opendataportal.at', port=80): Max retries exceeded with url: /dataset/8fbd4757-68a7-4d2c-bff7-cadf6639b934/resource/01bb4f6f-b0a4-461b-b5d9-3fca2215d6fe/download/registercontentconformanceclassgbasandat.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcc3dc15490>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='my-family-lineage.com', port=80): Max retries exceeded with url: /w/images/6/6c/Sangster_family_tree_2012-06-30.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca9ee1d990>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "[Errno 21] Is a directory: 'datasets/13759/'\n",
      "HTTPSConnectionPool(host='performance.cityofdavenportiowa.com', port=443): Max retries exceeded with url: /resource/2p3n-8zap.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fca9edff4d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='prtr.ec.europa.eu', port=80): Max retries exceeded with url: /rdf/WasteTransferMethodUsed.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca9ee15350>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='prtr.ec.europa.eu', port=80): Max retries exceeded with url: /rdf/Facility.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca9ee15990>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPSConnectionPool(host='www.galago-project.org', port=443): Max retries exceeded with url: /news/index.rdf (Caused by SSLError(CertificateError(\"hostname 'www.galago-project.org' doesn't match 'galago-project.org'\")))\n",
      "HTTPConnectionPool(host='sparql.tw.rpi.edu', port=80): Max retries exceeded with url: /vocab/datafaqs (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca9ee1f710>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='ckan.net', port=80): Max retries exceeded with url: /storage/f/file/d63ff6eb-d6fd-43fb-b713-02593010ebdc (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca9ee11f50>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='provenanceweb.org', port=80): Max retries exceeded with url: /ns/pml (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca9ee00c10>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='eol.taxonconcept.org', port=80): Max retries exceeded with url: /dos/771311fa322891f987ed366d8000d42b.ttl (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcc3dc2c350>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPSConnectionPool(host='performance.cityofdavenportiowa.com', port=443): Max retries exceeded with url: /resource/nn42-ukb5.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fca9edd5590>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPSConnectionPool(host='data.alaska.gov', port=443): Max retries exceeded with url: /resource/wh73-awse.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fca9edffa50>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPSConnectionPool(host='data.alaska.gov', port=443): Max retries exceeded with url: /resource/tber-ptz6.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fca9edff610>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPSConnectionPool(host='performance.cityofdavenportiowa.com', port=443): Max retries exceeded with url: /resource/5uub-7vre.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fca9edd6750>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='sparql.tw.rpi.edu', port=80): Max retries exceeded with url: /vocab/datafaqs (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcc3dc02050>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPSConnectionPool(host='performance.cityofdavenportiowa.com', port=443): Max retries exceeded with url: /resource/f99z-r68h.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fca9ee5cb50>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPSConnectionPool(host='performance.cityofdavenportiowa.com', port=443): Max retries exceeded with url: /resource/mcqq-286i.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fca9edd7190>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPSConnectionPool(host='performance.cityofdavenportiowa.com', port=443): Max retries exceeded with url: /resource/szu2-yvkg.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fca9edfc310>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='prtr.ec.europa.eu', port=80): Max retries exceeded with url: /rdf/Activity.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca9ee46c90>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='prtr.ec.europa.eu', port=80): Max retries exceeded with url: /rdf/lookuptables.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca9ee47c50>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "[Errno 21] Is a directory: 'datasets/13368/'\n",
      "HTTPSConnectionPool(host='skosmos.biblionaut.net', port=443): Max retries exceeded with url: /rest/v1/realfagstermer/data?uri=http%3A%2F%2Fdata.ub.uio.no%2Frealfagstermer%2Fc012676&format=text/turtle (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fca9eded910>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "[Errno 21] Is a directory: 'datasets/13796/'\n",
      "[Errno 21] Is a directory: 'datasets/14417/'\n",
      "HTTPConnectionPool(host='sparql.tw.rpi.edu', port=80): Max retries exceeded with url: /vocab/datafaqs (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca9ee1e190>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPSConnectionPool(host='performance.cityofdavenportiowa.com', port=443): Max retries exceeded with url: /resource/brdt-hn7k.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fca9ee5fd50>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='hub.tw.rpi.edu', port=80): Max retries exceeded with url: /source/hub/file/cr-full-dump/version/latest/conversion/purl-org-twc-hub.nt.gz (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca9ee14310>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPSConnectionPool(host='performance.cityofdavenportiowa.com', port=443): Max retries exceeded with url: /resource/vxui-y4hm.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fca9edff1d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='colinda.org', port=80): Max retries exceeded with url: /resource/conference/WWW/2012 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcc3dc2f590>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPSConnectionPool(host='performance.cityofdavenportiowa.com', port=443): Max retries exceeded with url: /resource/5rur-scr7.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fca9ee5db10>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPSConnectionPool(host='performance.cityofdavenportiowa.com', port=443): Max retries exceeded with url: /resource/ww5x-fjmk.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fca9edff4d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='prtr.ec.europa.eu', port=80): Max retries exceeded with url: /rdf/WasteTransfer.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca9ee45c10>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='wiki.prov.vic.gov.au', port=80): Max retries exceeded with url: /rdf/Public_Record_Office_Victoria_Semantic_Wiki.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcc3dbf7fd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='prtr.ec.europa.eu', port=80): Max retries exceeded with url: /rdf/PollutantTransferMethodUsed.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca9ee45c10>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='reference.data.gov.uk', port=80): Max retries exceeded with url: /gov-structure/organogram/?dept=treasury-solicitors&post=TS1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca9eded810>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPSConnectionPool(host='performance.cityofdavenportiowa.com', port=443): Max retries exceeded with url: /resource/m45h-nwyc.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fca9edffa50>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPSConnectionPool(host='performance.cityofdavenportiowa.com', port=443): Max retries exceeded with url: /resource/94a6-9ekd.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fca9ee5e390>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='eol.taxonconcept.org', port=80): Max retries exceeded with url: /dos/771311fa322891f987ed366d8000d42b.ttl (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca9edeffd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='data.opendataportal.at', port=80): Max retries exceeded with url: /dataset/8fbd4757-68a7-4d2c-bff7-cadf6639b934/resource/e551f4fd-b70a-4f2f-81d3-435b1b474355/download/registercontentconformanceclasslisalandcoverat.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcc3ddade90>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='data.opendataportal.at', port=80): Max retries exceeded with url: /dataset/8fbd4757-68a7-4d2c-bff7-cadf6639b934/resource/b21050c2-4240-49e3-ad6d-415d464c8cb9/download/registrymandatoryconformanceclasslisalandcoverat2.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcc3dc16ad0>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='www.gutenberg.org', port=80): Max retries exceeded with url: /ebooks/12345.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca9ee155d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='data.opendataportal.at', port=80): Max retries exceeded with url: /dataset/278cbe89-b1b1-449a-ab4d-527e555c80fd/resource/5d21a4fa-4efb-4d8b-b429-4c508e9f0658/download/registercontentconformanceclasszonetypecodeat2.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcc3ddadd50>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='lodcloud.tw.rpi.edu', port=80): Max retries exceeded with url: /purl.org/between-the-edges/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fca9edfd090>, 'Connection to lodcloud.tw.rpi.edu timed out. (connect timeout=None)'))\n",
      "HTTPSConnectionPool(host='performance.cityofdavenportiowa.com', port=443): Max retries exceeded with url: /resource/dhxq-u2iy.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fca9ee5c250>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "[Errno 21] Is a directory: 'datasets/13284/'\n",
      "HTTPSConnectionPool(host='performance.cityofdavenportiowa.com', port=443): Max retries exceeded with url: /resource/sjt9-8kuy.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fca9edd6490>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPSConnectionPool(host='performance.cityofdavenportiowa.com', port=443): Max retries exceeded with url: /resource/9kfy-3qnx.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fca9ee5d4d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='opendap.tw.rpi.edu', port=80): Max retries exceeded with url: /id/component/olfs (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca9ef9e810>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPSConnectionPool(host='performance.cityofdavenportiowa.com', port=443): Max retries exceeded with url: /resource/28y9-w79q.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fca9edfd090>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "[Errno 21] Is a directory: 'datasets/13334/'\n",
      "HTTPConnectionPool(host='provenanceweb.org', port=80): Max retries exceeded with url: /ns/pml (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca9ee14f50>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='data.opendataportal.at', port=80): Max retries exceeded with url: /dataset/278cbe89-b1b1-449a-ab4d-527e555c80fd/resource/dc01988f-52d0-44b3-9695-3360faed3738/download/registrymandatoryconformanceclasszonetypecodeat.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcc3dc16c50>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPSConnectionPool(host='performance.cityofdavenportiowa.com', port=443): Max retries exceeded with url: /resource/tr95-nw48.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fca9edec8d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='prtr.ec.europa.eu', port=80): Max retries exceeded with url: /rdf/UploadedReports.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca9ee15150>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPSConnectionPool(host='performance.cityofdavenportiowa.com', port=443): Max retries exceeded with url: /resource/bpan-z87k.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fca9edd4b10>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPSConnectionPool(host='performance.cityofdavenportiowa.com', port=443): Max retries exceeded with url: /resource/rs3n-u3ea.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fca9eded6d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='reference.data.gov.uk', port=80): Max retries exceeded with url: /technical-registry/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcc3dbf6310>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPSConnectionPool(host='performance.cityofdavenportiowa.com', port=443): Max retries exceeded with url: /resource/anfj-4snz.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fca9ee5d890>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPSConnectionPool(host='performance.cityofdavenportiowa.com', port=443): Max retries exceeded with url: /resource/wsh8-ca4b.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fca9edfc290>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPSConnectionPool(host='performance.cityofdavenportiowa.com', port=443): Max retries exceeded with url: /resource/uf8k-79zu.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fca9edffa50>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='futurewavehosting.com', port=3030): Max retries exceeded with url: /my-family-lineage/query (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca9ee1c350>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPSConnectionPool(host='performance.cityofdavenportiowa.com', port=443): Max retries exceeded with url: /resource/8s5g-czyk.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fca9edd49d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPSConnectionPool(host='data.alaska.gov', port=443): Max retries exceeded with url: /resource/vjxh-s5mf.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fca9edff750>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='my-family-lineage.com', port=80): Max retries exceeded with url: /w/RDF/classes.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca9ee1d990>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPSConnectionPool(host='simonstl.comfoaf.rdf', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fcc3dc35750>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='colinda.org', port=80): Max retries exceeded with url: /resource/conference/WWW/2012 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca9ee11810>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPSConnectionPool(host='performance.cityofdavenportiowa.com', port=443): Max retries exceeded with url: /resource/26nn-u7s5.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fca9edfea90>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "[Errno 21] Is a directory: 'datasets/13388/'\n",
      "HTTPSConnectionPool(host='performance.cityofdavenportiowa.com', port=443): Max retries exceeded with url: /resource/f87z-t8xq.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fca9edd55d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPSConnectionPool(host='performance.cityofdavenportiowa.com', port=443): Max retries exceeded with url: /resource/cs5q-hgrn.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fca9edfea90>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='hub.tw.rpi.edu', port=80): Max retries exceeded with url: /source/hub/file/cr-full-dump/version/latest/conversion/purl-org-twc-hub.nt.gz (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca9ee44b90>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='eol.taxonconcept.org', port=80): Max retries exceeded with url: /data/eol/eol_000001.ttl (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcc3dc2c050>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='my-family-lineage.com', port=80): Max retries exceeded with url: /w/RDF/classes.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca9ee11e50>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='lodcloud.tw.rpi.edu', port=80): Max retries exceeded with url: /source/tw-rpi-edu/file/cr-full-dump/version/latest/conversion/purl-org-twc-lodcloud.nt.gz (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fca9ee03f10>, 'Connection to lodcloud.tw.rpi.edu timed out. (connect timeout=None)'))\n",
      "HTTPConnectionPool(host='data.opendataportal.at', port=80): Max retries exceeded with url: /dataset/8fbd4757-68a7-4d2c-bff7-cadf6639b934/resource/0007462a-7b44-44b8-82cf-0747cfd91bf2/download/registryautomaticharvestingconformanceclasslisalandcoverclass.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcc3dc16610>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='my-family-lineage.com', port=80): Max retries exceeded with url: /w/images/d/d0/Adams.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca9ee13550>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "[Errno 21] Is a directory: 'datasets/15150/'\n",
      "HTTPConnectionPool(host='organogram.data.gov.uk', port=80): Max retries exceeded with url: /data/btp/2011-09-30/government-staff-and-salary-data-blank-template---October-2011.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca9ee14e10>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPSConnectionPool(host='performance.cityofdavenportiowa.com', port=443): Max retries exceeded with url: /resource/ftcy-kkwq.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fca9edefe90>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "[Errno 21] Is a directory: 'datasets/14084/'\n",
      "HTTPConnectionPool(host='hub.tw.rpi.edu', port=80): Max retries exceeded with url: /id/us/fed/agency/Department_of_Agriculture/crop/apples (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca9ee5e3d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPSConnectionPool(host='performance.cityofdavenportiowa.com', port=443): Max retries exceeded with url: /resource/x6v8-8huc.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fca9ee5db10>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPSConnectionPool(host='performance.cityofdavenportiowa.com', port=443): Max retries exceeded with url: /resource/tu7j-hja7.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fca9edfd010>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPSConnectionPool(host='performance.cityofdavenportiowa.com', port=443): Max retries exceeded with url: /resource/8spk-rg54.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fca9edd74d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='prtr.ec.europa.eu', port=80): Max retries exceeded with url: /rdf/FacilityReport.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca9ee44890>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='eol.taxonconcept.org', port=80): Max retries exceeded with url: /data/anno/anno_000001.ttl (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca9eded150>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPSConnectionPool(host='open.vocab.org', port=443): Max retries exceeded with url: /terms/ (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:992)')))\n",
      "HTTPConnectionPool(host='lodcloud.tw.rpi.edu', port=80): Max retries exceeded with url: /source/tw-rpi-edu/file/cr-full-dump/version/latest/conversion/purl-org-twc-lodcloud.nt.gz (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fca9ee26e90>, 'Connection to lodcloud.tw.rpi.edu timed out. (connect timeout=None)'))\n",
      "HTTPSConnectionPool(host='performance.cityofdavenportiowa.com', port=443): Max retries exceeded with url: /resource/rp6f-ffan.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fca9edd44d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='imash.leeds.ac.uk', port=80): Max retries exceeded with url: /tmp/AMOn+.zip (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca9edef110>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "[Errno 21] Is a directory: 'datasets/15414/'\n",
      "[Errno 21] Is a directory: 'datasets/13574/'\n",
      "HTTPSConnectionPool(host='performance.cityofdavenportiowa.com', port=443): Max retries exceeded with url: /resource/bpfa-8zxt.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fca9ee1c790>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='my-family-lineage.com', port=80): Max retries exceeded with url: /w/images/a/af/BruceWhealtonJr.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca9ee13110>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "[Errno 21] Is a directory: 'datasets/14806/'\n",
      "HTTPConnectionPool(host='provenanceweb.org', port=80): Max retries exceeded with url: /ns/pml (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcc3dc49350>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='hub.tw.rpi.edu', port=80): Max retries exceeded with url: /id/us/fed/agency/Department_of_Agriculture/crop/apples (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca9eddc190>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='provenanceweb.org', port=80): Max retries exceeded with url: /ns/pml (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca9ee45990>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPSConnectionPool(host='performance.cityofdavenportiowa.com', port=443): Max retries exceeded with url: /resource/t4na-zzbw.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fca9edd72d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='sparql.tw.rpi.edu', port=80): Max retries exceeded with url: /vocab/datafaqs (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca9ee5c210>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='prtr.ec.europa.eu', port=80): Max retries exceeded with url: /rdf/CompetentAuthority.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca9ee15150>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPSConnectionPool(host='performance.cityofdavenportiowa.com', port=443): Max retries exceeded with url: /resource/kehc-jr9w.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fca9edd72d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='semwebdev.keithalexander.co.uk', port=80): Max retries exceeded with url: /foaf.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcc3dc17390>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='sparql.tw.rpi.edu', port=80): Max retries exceeded with url: /vocab/datafaqs (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcc3dc72750>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='sparql.tw.rpi.edu', port=80): Max retries exceeded with url: /vocab/datafaqs (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca9ee1c390>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPConnectionPool(host='www.gutenberg.org', port=80): Max retries exceeded with url: /ebooks/12345.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcc3dc13750>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "HTTPSConnectionPool(host='opendata.oorlogsbronnen.nl', port=443): Max retries exceeded with url: /dataset/2b3f0e25-1c64-4f52-a8b0-862816351c0b/resource/3a7d9329-2120-4da7-b09f-5395ed15d13c/download/links_gvn_niod01_wo2thesaurus.nt (Caused by SSLError(CertificateError(\"hostname 'opendata.oorlogsbronnen.nl' doesn't match 'documentwijzer.raadvanalmere.nl'\")))\n",
      "HTTPConnectionPool(host='prtr.ec.europa.eu', port=80): Max retries exceeded with url: /rdf/ExternalLinks.rdf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca9ee46110>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n"
     ]
    }
   ],
   "source": [
    "for code in errors_codes:\n",
    "    if len(code) >= 20:\n",
    "        print(code)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": []
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.12"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
